name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0  # Use a newer version of MongoDB
        ports:
          - 27017:27017
        options: >-
          --health-cmd="curl --silent --fail localhost:27017"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Wait for MongoDB to be ready
      run: |
        until curl --silent --fail mongodb:27017; do
          echo "Waiting for MongoDB to be ready..."
          sleep 2
        done
        echo "MongoDB is ready!"

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Check MongoDB container logs
      run: |
        docker ps -a
        docker logs $(docker ps -q --filter "ancestor=mongo:5.0")

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
